Class REBarrel : ExplosiveBarrel replaces ExplosiveBarrel
{
	Default
	{
		Health 25;
		+PUSHABLE
		DamageFactor "Fire", 2.0;
		DeathSound "world/barrelx";
	}
	States
	{
	Spawn:
		TNT1 A 0 NoDelay A_Jump(256,1,2,3,4);
		PROP A -1;
		BARA A -1;
		BARB A -1;
		BARC A -1;
		Stop;
	Death:
		//"####" "#" 0 A_JumpIf(Scale.X > 1.2, 2);
		//"####" "#" 2 Bright A_SetScale(Scale.X + 0.04,1);
		//Loop;
		EXP1 A 2 BRIGHT A_SetTranslucent(0.85,1);
		#### BC 2 BRIGHT A_ScreamAndUnblock();
		#### DE 2 BRIGHT;
		#### F 2 BRIGHT A_Explode(128,128,XF_HURTSOURCE);
		#### GHIJKL 2 BRIGHT;
		#### M 2 BRIGHT A_SetTranslucent(0.55,1);
		#### N 2 BRIGHT A_SetTranslucent(0.20,1);
		Stop;
	}
}
