//Giving the item to the player
Class RE2Handler : EventHandler
{
	// bool yesOrNo(double probabilityOfYes) { return random()%100 < (probabilityOfYes * 100);	}
	// if(yesOrNo(0.06)) { e.Thing.A_SpawnItemEx("",0,0,random(6,14)); }

	/*Override Void PlayerSpawned(PlayerEvent e)
	{
		PlayerInfo player = players[e.PlayerNumber];
		player.mo.A_SetBlend("0 0 0",1.0,105);
	}
	Override Void PlayerDied(PlayerEvent e)
	{
		PlayerInfo player = players[e.PlayerNumber];
		player.mo.GiveInventory("BackInBlack",1);
	}*/
	Override Void PlayerRespawned(PlayerEvent e)
	{
		PlayerInfo player = players[e.PlayerNumber];
		//player.mo.TakeInventory("PowerLightAmp", 1);
		player.mo.TakeInventory("FireDeathEffect", 1);
	}

	override void WorldThingSpawned(WorldEvent e)
	{
		If(e.Thing is "PlayerPawn" && !e.Thing.FindInventory("GM79"))
		{
			e.Thing.GiveInventory("FlameRounds",0);
			e.Thing.GiveInventory("AcidRounds",0);
			e.Thing.GiveInventory("FreezeRounds",0);
		}

		If(e.thing && e.thing.GetClass() == "DeadMarine" || e.thing.GetClass() == "GibbedMarine" || e.thing.GetClass() == "GibbedMarineExtra")
		{
			switch(Random(0,4))
			{
			case 0:
				e.thing.Spawn("HandgunAmmo_15", e.thing.pos + (15, 0, 0));
				break;
			case 1:
				e.thing.Spawn("W870", e.thing.pos + (15, 0, 0));
				break;
			case 2:
				e.thing.Spawn("ShotgunShells_7", e.thing.pos + (15, 0, 0));
				break;
			case 3:
				e.thing.Spawn("LightningHawk", e.thing.pos + (15, 0, 0));
				break;
			case 4:
				e.thing.Spawn("MQ11", e.thing.pos + (15, 0, 0));
				break;
			}
		}
	}

    override void WorldThingDied(WorldEvent e) // Credits to jarewill on the ZDoom Forums
    {
        If(e.Inflictor && e.Inflictor.DamageType == "Fire")
        {
            e.Thing.GiveInventory("FireDeathEffect",1);
        }
    }

	override void CheckReplacement(ReplaceEvent e)
	{
		if (e.Replacee == "Fist")						e.Replacement = "CombatKnife";
		else if (e.Replacee == "Chainsaw")					e.Replacement = "SparkShot";
		else if (e.Replacee == "Pistol")					e.Replacement = "Matilda";
		else if (e.Replacee == "Shotgun")					e.Replacement = "ShotgunDrop";
		else if (e.Replacee == "SuperShotgun")					e.Replacement = "LightningHawk";
		else if (e.Replacee == "Chaingun")					e.Replacement = "ChaingunDrop";
		else if (e.Replacee == "RocketLauncher")				e.Replacement = "GM79";
		else if (e.Replacee == "PlasmaRifle")					e.Replacement = "ChemicalFlameThrower";
		else if (e.Replacee == "BFG9000")					e.Replacement = "ATRL";

		else if (e.Replacee == "HealthBonus")					e.Replacement = "BonusSpawner";
		else if (e.Replacee == "Stimpack")					e.Replacement = "StimpackSpawner";
		else if (e.Replacee == "Medikit")					e.Replacement = "MedikitSpawner";		
		else if (e.Replacee == "SoulSphere")					e.Replacement = "SoulSphereSpawner";	

		else if (e.Replacee == "ArmorBonus")					e.Replacement = "BonusSpawner";
		else if (e.Replacee == "GreenArmor")					e.Replacement = "ArmorVest";
		else if (e.Replacee == "BlueArmor")					e.Replacement = "PoliceArmor";	

		//else if (e.Replacee == "RadSuit")					e.Replacement = "BlueHerb";
		else if (e.Replacee == "Infrared")					e.Replacement = "BerserkDrop";
		/*else if (e.Replacee == "AllMap")					e.Replacement = "AllMap";
		else if (e.Replacee == "InvulnerabilitySphere")				e.Replacement = "InvulnerabilitySphere";*/
		else if (e.Replacee == "BlurSphere")					e.Replacement = "BerserkDrop";
		else if (e.Replacee == "Berserk")					e.Replacement = "BerserkDrop";	
		else if (e.Replacee == "MegaSphere")					e.Replacement = "SoulSphereSpawner";

		else if (e.Replacee == "Clip")						e.Replacement = "ClipDrop";
		else if (e.Replacee == "ClipBox")					e.Replacement = "ClipDrop";
		else if (e.Replacee == "Shell")						e.Replacement = "ShellDrop";
		else if (e.Replacee == "ShellBox")					e.Replacement = "ShellDrop";
		else if (e.Replacee == "RocketAmmo")					e.Replacement = "RocketAmmoDrop";
		else if (e.Replacee == "RocketBox")					e.Replacement = "RocketAmmoDrop";
		else if (e.Replacee == "Cell")						e.Replacement = "CellDrop";
		else if (e.Replacee == "CellPack")					e.Replacement = "CellDrop";
		else if (e.Replacee == "Backpack")					e.Replacement = "BackpackSpawner";
	}
}

Class FireDeathEffect : Inventory // Credits to jarewill on the ZDoom Forums
{
	override void AttachToOwner(Actor other)
	{
		self.height = other.height; //Store the monster's height
		Super.AttachToOwner(other);
	}
	override void DoEffect()
	{
		Super.DoEffect();
		If(Owner && !(Owner is "ExplosiveBarrel") && !(Owner is "LostSoul") && !(Owner is "PainElemental") && !(Owner is "CyberDemon") && !(Owner is "SpiderMastermind") && !Owner.FindState("Death.Fire") && !Owner.FindState("Burn") )
		{
			Owner.bFLY = False; Owner.bNOGRAVITY = False; Owner.bNOBLOOD = True; // Set relevant flags so the monster cannot be damaged, can't fly and doesn't spawn blood.
			Owner.height = self.height; //Reset the height
			Owner.A_SetTranslation("Scorched"); //Set a color translation
		}
	}
}
